---
require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 20
  Exclude:
    - 'spec/*'
    - 'spec/**/*'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Metrics/ParameterLists:
  Max: 5

Style/CommandLiteral:
  Exclude:
    - 'test_database.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false # We never ended up being forced to do this for Ruby 3.x

Style/MultilineBlockChain:
  Exclude:
    - 'spec/integration_spec.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'departure.gemspec'
    - 'test_database.rb'

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/RedundantPercentQ:
  Exclude:
    - 'departure.gemspec'

Style/SymbolArray:
  Enabled: false
